name: Matteo Album

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
  push:
    paths:
      - matteo/album/**
  schedule:
    - cron: "0 0 * * *"

jobs:
  album:
    name: Matteo Album
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: docker://ghcr.io/alexcarrega/matteo-album:latest
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_HOST: ${{ vars.FTP_HOST }}
          WEBDISK_USERNAME: ${{ secrets.WEBDISK_USERNAME }}
          WEBDISK_PASSWORD: ${{ secrets.WEBDISK_PASSWORD }}
          WEBDISK_URL: ${{ vars.WEBDISK_URL }}
