name: Matteo Album

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
  push:
    paths:
      - matteo/album/**
  schedule:
    - cron: "0 0 * * *"

jobs:
  album:
    name: Matteo Album
    runs-on: ubuntu-latest
    container: ghcr.io/alexcarrega/matteo-album:latest
    permissions:
      packages: write
      contents: read
    env:
      FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      FTP_HOST: ${{ secrets.FTP_HOST }}
    steps:
      - run: bash ./entrypoint.sh
