name: Matteo Album

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
  push:
    paths:
      - matteo/album/**
  schedule:
    - cron: "0 0 * * *"

jobs:
  album:
    runs-on: ubuntu-latest
    container: ghcr.io/alexcarrega/matteo-album:latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
